version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment: 
      DATABASE_NAME: paocombits
      DATABASE_USER: paocombits
      DATABASE_PASSWORD: admin
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
    networks:
      - paocombits_api
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: paocombits
      MYSQL_USER: paocombits
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - paocombits_api
 
volumes:
  mysql_data: 

networks:
  paocombits_api: