CREATE TABLE IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    content LONGTEXT,
    thumbnail VARCHAR(800),
    createdBy VARCHAR(255),
    createdOn DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NULL,
    email VARCHAR(500) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    adm INT DEFAULT 0,
    createdOn DATETIME DEFAULT CURRENT_TIMESTAMP
);
